spring:
  application:
    name: weski
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/ski_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/ski_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: master
    password: master
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
weather:
  api:
    key: p6zNXOJrrBY4cuX7OYtdDMtmR8hiGeUaBLf0z6BXnm/qniV8wB0SuPwBgqKDTKV/24EW7xiRY3DCS21Ess/42Q==
tamp:
  api:
    key: hzztwqD56d3rBN9hEo1rY1yJiCqtfWY55Obn4Ocj
